#!/bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
eval "$(conda shell.bash hook)"
conda activate nhts-env
python $SCRIPT_DIR/src/nhts.py "$@"                                                                      

